image: mcr.microsoft.com/dotnet/sdk:6.0

include:
  - project: 'edouard-paumier/student-ci'
    ref: master
    file: '/student-ci.gitlab-ci.yml'

stages:
  - compile
  - test
  - grade
  - archive

variables:
  VERSION: '3'

compile:
  stage: compile
  script:
    - dotnet build shard.sln
  interruptible: true
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths: 
      - "*/bin/*/*/*"

.limitted:
  allow_failure: true
  interruptible: true
  timeout: 6 minutes
  rules:
  - if: $CI_COMMIT_BRANCH == "prod"
    when: on_success
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
    when: delayed
    start_in: 1 day
  - when: on_success

.test:
  extends: .limitted
  stage: test
  script:
    - dotnet test --logger trx --filter "$TEST_FILTER" shard.sln
  after_script:
    - bash ./extractTestResults.sh $TEST_REPORT
  artifacts:
    when: always
    paths: 
    - tests/$TEST_REPORT.txt

test:version:
  variables:
    TEST_FILTER: (grading=true)&(version=$VERSION)
    TEST_REPORT: version$VERSION
  extends: .test

test:full:
  variables:
    TEST_FILTER: grading=true
    TEST_REPORT: full
  extends: .test
  
test:coverage:
  stage: test
  extends: .limitted
  before_script:
    - dotnet tool install -g dotnet-reportgenerator-globaltool
  script:
    - dotnet test --filter "grading!=true" --settings coverlet.runsettings shard.sln
  after_script:
    - /root/.dotnet/tools/reportgenerator "-reports:*/TestResults/*/coverage.cobertura.xml" "-targetdir:./coverage" "-reporttypes:Html"
    - cat coverage/index.htm | tr '\n' ' ' | sed -E "s/^.*Line coverage:<\/th>\\s*<td[^>]*>(([[:digit:]]|\.)+)%.*$/\1/" | awk '{ print $1/100 }' > coverage/line_rate.txt
  artifacts:
    when: always
    paths: 
    - "coverage/*"
